ARG BASE_IMAGE="ubuntu:latest"
# hadolint ignore=DL3006
FROM ${BASE_IMAGE} AS build
ARG DEBIAN_FRONTEND=noninteractive
ARG DEBCONF_NOWARNINGS="yes"
WORKDIR /build
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get --no-install-recommends -yq install \
      build-essential \
      devscripts \
      debhelper \
      dpkg-dev \
      dh-make \
      ca-certificates \
      $(cat apt-prerequisites) && \
    rm -rf /var/lib/apt/lists/*
